---
- hosts: all
  become: yes
  roles:
      - deploy.setup
      - deploy.project
      - deploy.finalize
  vars:
    deploy:
      project:
        root: '/tmp/test_deploy'
        name: 'My Project'
        scm: 'rsync'
        source: "dist"
        keep_previous_releases: 3
        copy_previous_release: True
        writable_dirs:
          - src: "var/files"
        shared_dirs:
          - "var/files"
        shared_files: []
        templated_files:
          -
            source: "config/settings.ini.j2"
            dest: "config/settings.ini"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
      finalize:
        required_sudo: False
        commands: []
        to_be_restarted_services: []
    permission_model: 'chmod'